volumes:
  django_template_local_postgres_data: {}

services:
  postgres:
      build:
        context: .
        dockerfile: ./compose/production/postgres/Dockerfile
      container_name: django_template_postgres_local
      volumes:
        - django_template_local_postgres_data:/var/lib/postgresql/data
        - ./data/backups:/backups
      env_file:
        - ./envs/local/postgres

  redis:
    image: redis:latest
    container_name: django_template_redis_local

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django_template_django_local
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/:/app
      - ./data/logs/:/logs
      - ./data/common/:/common
      - ./data/media/:/media

    env_file:
      - ./envs/local/django
      - ./envs/local/postgres
    ports:
      - "8000:8000"
    command: /start

  celery:
    profiles: ["celery"]
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django_template_celery_local
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/:/app
      - ./data/logs/:/logs
      - ./data/common/:/common
      - ./data/media/:/media
    env_file:
      - ./envs/local/django
      - ./envs/local/postgres
    command: /celery_start
