name: Test and Propose Release

on:
  push:
    branches:
      - dev

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-secret-key
      BACKEND_DOMAIN: localhost
      BACKEND_URL: http://localhost
      BACKEND_SLUG: dev
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: sqlite:///test_db.sqlite3
      DJANGO_SETTINGS_MODULE: core.settings.localtest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --frozen --no-install-project

      - name: Run Django tests
        run: docker compose -f local.yml run --rm django uv run manage.py test

      - name: Create or update PR into master
        if: success()
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Sync dev to master - ${{ github.sha }}
          pr_body: |
            ## Summary
            - Automated PR to merge latest dev changes into master
            - Commit: ${{ github.sha }}
            - Message: ${{ github.event.head_commit.message }}
            
            ## Automated Notice
            Tests succeeded in CI prior to opening this pull request.
